### ISSUE TITLE
I'm getting `Must enable debugger if running --replay-debug.` on MacOS when I'm trying to debug.

### ISSUE THREAD

**Issue by vladimir-trifonov** [mrkmarron/RFSDemoJS#3]
## Setup:
MacOS Sierra 10.12.4
Node version: v8.0.0-nightly201704205bd7d4d626
VSCode version: Version 1.12.0-insider (1.12.0-insider)

## Issue:
I get `Must enable debugger if running --replay-debug.` in the debug console when trying to debug.

### Debug console:
`/Users/xxx/.nvs/nvs --debug-brk=33701 run chakracore-nightly --nolazy --break-first --replay-debug=/Users/xxx/Projects/RFSDemoJS/_diagnosticTraces/emitOnLogWarn_graceful-fs_line-78_column-13_bucket-0/trace-0 .vscode/empty.js 
Must enable debugger if running --replay-debug.
Run with "-h" for help with flags.`

**Comment by mrkmarron** [comment]
Hi and thanks for the report. I was just able to reproduce this and it looks like an issue with the merge in commit ac1e9e0 in Node-ChakraCore. We should be able to get a fix out shortly. 

As a temporary workaround I verified that nightly build [v8.0.0-nightly20170415265fc0bedc](https://nodejs.org/download/chakracore-nightly/v8.0.0-nightly20170415265fc0bedc/) does not have this issue. You can use NVS to get this with the following commands:
```
> nvs add chakracore-nightly/v8.0.0-nightly20170415265fc0bedc
> nvs use chakracore-nightly/8.0.0-nightly20170415265fc0bedc
```
And also updating the `runtimeArgs` in the launch.json configuration to use this version as well:
```
"runtimeArgs": [
          "run",
          "chakracore-nightly/v8.0.0-nightly20170415265fc0bedc",
          "--nolazy",
          "--break-first", 
          "--replay-debug=${workspaceRoot}/_diagnosticTraces/emitOnLogWarn_graceful-fs_line-78_column-13_bucket-0/trace-0"
      ],
```

**Comment by vladimir-trifonov** [comment]
Yes, you are right. Thank you for the solution.

**Comment by mrkmarron** [comment]
Updated the instructions to point to our stable (w/ legacy debug support) Node-ChakraCore release until we finish TTD support in new inspector protocol.
